name:       pretty-printer
version:    '0.1.0.0'
category:   Text
author:     Kove W. Ochre-Salter
maintainer: kove.w.o.salter@gmail.com
copyright:  (c) Kove W. Ochre-Salter, 2019
license:    MIT
github:     kove-w-o-salter/pretty-printer

extra-source-files:
- README.md

dependencies:
- base >=4.7 && <5
- text >= 1.2.3.1
- bytestring >= 0.10.8.2
- mtl >= 2.2.2
- lens >= 4.17

library:
  source-dirs: src
  exposed-modules:
  - Text.PrettyPrinter
  - Text.PrettyPrinter.Internal
